#!/bin/sh

tenernombresarchivos(){ # archivo posicion_enlace_simbolico
	 echo "$(ls -ao $1 | tr -s ' ' | cut -d' ' -f $2)"
}

if [[ "$1" == "" ]]; then
	echo "Se requiere argumento de libreria."
else
	libreria="$(basename $1 | cut -d "." -f 1)"
	rm -rvf "$libreria"
	libs="$(ldd -v "$1")"
	if [[ "$libs" == "" ]]; then
		echo "No se encontro la libreria"
	else
		dependencias="$(echo "$libs" | grep ":" | grep "/" | cut -d$'\t' -f2 | cut -d$':' -f1)"
		echo "$dependencias" | while read archivo; do
			nombre_completo="$(tenernombresarchivos $archivo 8)"
			nombre_simbolico="$(tenernombresarchivos $archivo 10)"
			echo $nombre_completo
			if [[ "$nombre_simbolico" != "" ]]; then
				echo "$(dirname $nombre_completo)/$nombre_simbolico"
			fi
		done | while read ruta; do
			echo $ruta
			absoluta="$libreria$(dirname $ruta)"
			mkdir -pv "$absoluta"
			cp -Rvf $ruta "$absoluta"
		done
		cd "$libreria"
		pwd -P
	fi
fi
